# Generated by Django 4.2.5 on 2023-09-21 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='allStarStatus',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='clubName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='fileCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='firstYearOfPlay',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='franchiseName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='locationName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='parentOrgId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='parentOrgName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='shortName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='teamName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.division'),
        ),
        migrations.AddField(
            model_name='teams',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.league'),
        ),
        migrations.AddField(
            model_name='teams',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.sport'),
        ),
        migrations.AddField(
            model_name='teams',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.venue'),
        ),
    ]
