# Generated by Django 4.2.5 on 2023-10-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0002_alter_teams_abbreviation_alter_teams_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ManyToManyField(null=True, to='Stats.season'),
        ),
    ]
