# Generated by Django 4.2.5 on 2023-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0002_division_league_sport_venue_teams_abbreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='season',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
