# Generated by Django 4.2.5 on 2023-09-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0003_venue_active_venue_link_venue_name_venue_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='league',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='conferencesInUse',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='divisionsInUse',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='hasPlayoffPoints',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='hasSplitSeason',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='hasWildCard',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='numGames',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='numTeams',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='numWildcardTeams',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='orgCode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='sortOrder',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.sport'),
        ),
        migrations.AddField(
            model_name='teams',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='league',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.season'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.season'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.season'),
        ),
    ]
