# Generated by Django 4.2.5 on 2023-09-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0004_season_league_abbreviation_league_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='nameShort',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='seasonState',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
