# Generated by Django 4.2.5 on 2023-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0006_division_abbreviation_division_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='abbreviation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='activeStatus',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='sortOrder',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
