# Generated by Django 4.2.5 on 2023-09-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0007_sport_abbreviation_sport_activestatus_sport_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='allStarDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='firstDate2ndHalf',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='gameLevelGamedayType',
            field=models.CharField(max_length=1, null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='hasWildCard',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='lastDate1stHalf',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='offSeasonEndDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='offseasonStartDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='postSeasonEndDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='postSeasonStartDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='preSeasonEndDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='preSeasonStartDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='qualifierOutsPitched',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='qualifierPlateAppearances',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='regularSeasonEndDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='regularSeasonStartDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='seasonEndDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='seasonLevelGamedayType',
            field=models.CharField(max_length=1, null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='seasonStartDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='springEndDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AddField(
            model_name='season',
            name='springStartDate',
            field=models.DateField(null=type),
            preserve_default=type,
        ),
        migrations.AlterField(
            model_name='season',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
