# Generated by Django 4.2.5 on 2023-09-22 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0008_season_allstardate_season_firstdate2ndhalf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('shortName', models.CharField(max_length=50, null=True)),
                ('fullName', models.CharField(max_length=50, null=True)),
                ('abbrev', models.CharField(max_length=1, null=True)),
                ('code', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('formalName', models.CharField(max_length=50, null=True)),
                ('displayName', models.CharField(max_length=50, null=True)),
                ('pitcher', models.BooleanField(null=True)),
                ('gamePosition', models.BooleanField(null=True)),
                ('fielder', models.BooleanField(null=True)),
                ('outfield', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fullName', models.CharField(max_length=50, null=True)),
                ('firstName', models.CharField(max_length=50, null=True)),
                ('lastName', models.CharField(max_length=50, null=True)),
                ('primaryNumber', models.CharField(max_length=3, null=True)),
                ('useName', models.CharField(max_length=50, null=True)),
                ('boxscoreName', models.CharField(max_length=50, null=True)),
                ('nickName', models.CharField(max_length=50, null=True)),
                ('mlbDebutDate', models.CharField(max_length=50, null=True)),
                ('nameFirstLast', models.CharField(max_length=50, null=True)),
                ('firstLastName', models.CharField(max_length=50, null=True)),
                ('lastFirstName', models.CharField(max_length=50, null=True)),
                ('lastInitName', models.CharField(max_length=50, null=True)),
                ('initLastName', models.CharField(max_length=50, null=True)),
                ('fullFMLName', models.CharField(max_length=50, null=True)),
                ('fullLFMName', models.CharField(max_length=50, null=True)),
                ('currentTeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.teams')),
                ('primaryPosition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.position')),
            ],
        ),
    ]
