# Generated by Django 4.2.5 on 2023-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0009_position_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='batSide',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birthCity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birthCountry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birthDate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='currentAge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='isPlayer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='isVerified',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='middleName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nameSlug',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pitchHand',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pronunciation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='strikeZoneBottom',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='strikeZoneTop',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='useLastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
