# Generated by Django 4.2.5 on 2023-09-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0010_player_active_player_batside_player_birthcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
