# Generated by Django 4.2.5 on 2023-09-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0011_alter_position_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='abbrev',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
