# Generated by Django 4.2.5 on 2023-09-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0012_alter_position_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='abbrev',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
