# Generated by Django 4.2.5 on 2023-09-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0013_alter_position_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='abbrev',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='displayName',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='formalName',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='fullName',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='shortName',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='type',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
