# Generated by Django 4.2.5 on 2023-09-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0014_alter_position_abbrev_alter_position_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='id',
            new_name='seasonId',
        ),
    ]
