# Generated by Django 4.2.5 on 2023-09-25 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0015_rename_id_season_seasonid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='hasWildCard',
            new_name='hasWildcard',
        ),
    ]
