# Generated by Django 4.2.5 on 2023-09-25 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0016_rename_haswildcard_season_haswildcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='sportId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.sport'),
        ),
    ]
