# Generated by Django 4.2.5 on 2023-09-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0017_season_sportid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
