# Generated by Django 4.2.5 on 2023-09-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0018_alter_venue_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='hasWildCard',
            new_name='hasWildcard',
        ),
    ]
