# Generated by Django 4.2.5 on 2023-09-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0019_rename_haswildcard_division_haswildcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='numPlayoffTeams',
            field=models.IntegerField(null=True),
        ),
    ]
