# Generated by Django 4.2.5 on 2023-09-29 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0020_division_numplayoffteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='springLeague',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='springLeague', to='Stats.league'),
        ),
        migrations.AddField(
            model_name='teams',
            name='springVenue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='springVenue', to='Stats.venue'),
        ),
    ]
