# Generated by Django 4.2.5 on 2023-10-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0021_teams_springleague_teams_springvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='deathCity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='deathCountry',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='deathDate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='deathStateProvince',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='lastPlayedDate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
