# Generated by Django 4.2.5 on 2023-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0022_player_deathcity_player_deathcountry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birthStateProvince',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
