# Generated by Django 4.2.5 on 2023-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0023_player_birthstateprovince'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nameSuffix',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='nameTitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
