# Generated by Django 4.2.5 on 2023-10-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0024_player_namesuffix_player_nametitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nameMatrilineal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
