# Generated by Django 4.2.5 on 2023-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0025_player_namematrilineal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fullFMLName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='initLastName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
