# Generated by Django 4.2.5 on 2023-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0026_alter_player_fullfmlname_alter_player_initlastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fullLFMName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='initLastName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
