# Generated by Django 4.2.5 on 2023-10-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0028_player_draftyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='namePrefix',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
