# Generated by Django 4.2.5 on 2023-10-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stats', '0029_player_nameprefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='season',
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jerseyNumber', models.TextField(max_length=5, null=True)),
                ('status', models.BooleanField(null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.player')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.position')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Stats.season')),
            ],
        ),
        migrations.AddField(
            model_name='teams',
            name='season',
            field=models.ManyToManyField(null=True, to='Stats.season'),
        ),
    ]
