from django.db import models
import statsapi as sap
from Stats.sources.mlbClasses import MLB
# Create your models here.
aux = MLB()
class Teams(models.Model):#hecho
    allStarStatus = models.CharField(max_length=1,null=True)
    id = models.IntegerField(primary_key=True,unique=True,blank=False)
    name = models.CharField(max_length=50,null=True)
    link = models.CharField(max_length=50, null=True)
    season = models.ForeignKey('Season',on_delete=models.CASCADE,null=True)
    venue = models.ForeignKey('Venue',on_delete=models.CASCADE,null=True)
    teamCode = models.CharField(max_length=10,null=True)
    fileCode = models.CharField(max_length=10,null=True)
    abbreviation = models.CharField(max_length=10,null=True)
    teamName = models.CharField(max_length=50,null=True)
    locationName = models.CharField(max_length=50,null=True)
    firstYearOfPlay = models.CharField(max_length=4,null=True)
    league = models.ForeignKey('League',on_delete=models.CASCADE,null=True)
    division = models.ForeignKey('Division',on_delete=models.CASCADE,null=True)
    sport = models.ForeignKey('Sport',on_delete=models.CASCADE,null=True)
    shortName = models.CharField(max_length=50,null=True)
    parentOrgName = models.CharField(max_length=50,null=True)
    parentOrgId = models.IntegerField(null=True)
    franchiseName = models.CharField(max_length=50,null=True)
    clubName = models.CharField(max_length=50,null=True)
    active = models.BooleanField(null=True)
    springLeague = models.ForeignKey('League',on_delete=models.CASCADE,null=True,related_name='springLeague')
    springVenue = models.ForeignKey('Venue',on_delete=models.CASCADE,null=True,related_name='springVenue')
class Venue(models.Model):#hecho
    id = models.IntegerField(primary_key=True,unique=True,blank=False)
    name = models.CharField(max_length=55,null=True)
    link  = models.CharField(max_length=50,null=True)
    active = models.BooleanField(null=True)
    season = models.ForeignKey('Season',on_delete=models.CASCADE,null=True)
class League(models.Model):#hecho
    id = models.IntegerField(primary_key=True, unique=True, blank=False)
    name = models.CharField(max_length=50, null=True)
    link = models.CharField(max_length=50, null=True)
    abbreviation = models.CharField(max_length=10, null=True)
    hasWildCard = models.BooleanField(null=True)
    hasSplitSeason = models.BooleanField(null=True)
    numGames = models.IntegerField(null=True)
    hasPlayoffPoints = models.BooleanField(null=True)
    numTeams = models.IntegerField(null=True)
    numWildcardTeams = models.IntegerField(null=True)
    season = models.ForeignKey('Season',on_delete=models.CASCADE,null=True)
    orgCode = models.CharField(max_length=10,null=True)
    conferencesInUse = models.BooleanField(null=True)
    divisionsInUse = models.BooleanField(null=True)
    sport = models.ForeignKey('Sport',on_delete=models.CASCADE,null=True)
    sortOrder = models.IntegerField(null=True)
    active = models.BooleanField(null=True)
    nameShort = models.CharField(max_length=50,null=True)
    seasonState = models.CharField(max_length=50,null=True)
class Division(models.Model):#hecho
    id = models.IntegerField(primary_key=True, unique=True, blank=False)
    name = models.CharField(max_length=50, null=True)
    season = models.ForeignKey('Season', on_delete=models.CASCADE, null=True)
    nameShort = models.CharField(max_length=50, null=True)
    link = models.CharField(max_length=50, null=True)
    abbreviation = models.CharField(max_length=10, null=True)
    league = models.ForeignKey('League', on_delete=models.CASCADE, null=True)
    sport = models.ForeignKey('Sport', on_delete=models.CASCADE, null=True)
    hasWildcard = models.BooleanField(null=True)
    sortOrder = models.IntegerField(null=True)
    numPlayoffTeams = models.IntegerField(null=True)
    active = models.BooleanField(null=True)
class Sport(models.Model):#hecho
    id = models.IntegerField(primary_key=True, unique=True, blank=False)
    code = models.CharField(max_length=10,null=True)
    link = models.CharField(max_length=50, null=True)
    name = models.CharField(max_length=50, null=True)
    abbreviation = models.CharField(max_length=10, null=True)
    sortOrder = models.IntegerField(null=True)
    activeStatus = models.BooleanField(null=True)
class Season(models.Model):#hecho
    seasonId = models.IntegerField(primary_key=True, unique=True, blank=False)
    hasWildcard = models.BooleanField(null=True)
    preSeasonStartDate = models.DateField(null=type)
    preSeasonEndDate = models.DateField(null=type)
    seasonStartDate = models.DateField(null=type)
    springStartDate = models.DateField(null=type)
    springEndDate = models.DateField(null=type)
    regularSeasonStartDate = models.DateField(null=type)
    lastDate1stHalf = models.DateField(null=type)
    allStarDate = models.DateField(null=type)
    firstDate2ndHalf = models.DateField(null=type)
    regularSeasonEndDate = models.DateField(null=type)
    postSeasonStartDate = models.DateField(null=type)
    postSeasonEndDate = models.DateField(null=type)
    seasonEndDate = models.DateField(null=type)
    offseasonStartDate = models.DateField(null=type)
    offSeasonEndDate = models.DateField(null=type)
    seasonLevelGamedayType = models.CharField(max_length=1,null=type)
    gameLevelGamedayType = models.CharField(max_length=1,null=type)
    qualifierPlateAppearances = models.FloatField(null=True)
    qualifierOutsPitched = models.FloatField(null=True)
    sportId = models.ForeignKey('Sport', on_delete=models.CASCADE, null=True)
class Player(models.Model):
    id = models.IntegerField(primary_key=True, unique=True, blank=False)
    fullName = models.CharField(max_length=50,null=True)
    firstName = models.CharField(max_length=50,null=True)
    lastName = models.CharField(max_length=50,null=True)
    birthDate = models.CharField(max_length=50,null=True)
    currentAge = models.IntegerField(null=True)
    birthCity = models.CharField(max_length=50,null=True)
    birthCountry = models.CharField(max_length=50,null=True)
    height = models.CharField(max_length=50,null=True)
    weight = models.IntegerField(null=True)
    active = models.BooleanField(null=True)
    primaryNumber = models.CharField(max_length=3,null=True)
    currentTeam = models.ForeignKey('Teams',on_delete=models.CASCADE,null=True)
    primaryPosition = models.ForeignKey('Position',on_delete=models.CASCADE,null=True)
    useName = models.CharField(max_length=50,null=True)
    useLastName = models.CharField(max_length=50,null=True)
    middleName = models.CharField(max_length=50,null=True)
    boxscoreName = models.CharField(max_length=50,null=True)
    nickName = models.CharField(max_length=50,null=True)
    gender = models.CharField(max_length=1,null=True)
    isPlayer = models.BooleanField(null=True)
    isVerified = models.BooleanField(null=True)
    pronunciation = models.CharField(max_length=50,null=True)
    mlbDebutDate = models.CharField(max_length=50,null=True)
    batSide = models.CharField(max_length=1,null=True)
    pitchHand = models.CharField(max_length=1,null=True)
    nameFirstLast = models.CharField(max_length=50,null=True)
    nameSlug = models.CharField(max_length=50,null=True)
    firstLastName = models.CharField(max_length=50,null=True)
    lastFirstName = models.CharField(max_length=50,null=True)
    lastInitName = models.CharField(max_length=50,null=True)
    initLastName = models.CharField(max_length=50,null=True)
    fullFMLName = models.CharField(max_length=50,null=True)
    fullLFMName = models.CharField(max_length=50,null=True)
    strikeZoneTop = models.FloatField(null=True)
    strikeZoneBottom = models.FloatField(null=True)
class Position(models.Model):#hecho
    shortName = models.TextField(max_length=50, null=True)
    fullName = models.TextField(max_length=50, null=True)
    abbrev = models.TextField(max_length=10,null=True)
    code = models.TextField(primary_key=True, unique=True, blank=False)
    type = models.TextField(max_length=50, null=True)
    formalName = models.TextField(max_length=50, null=True)
    displayName = models.TextField(max_length=50, null=True)
    pitcher = models.BooleanField(null=True)
    gamePosition = models.BooleanField(null=True)
    fielder = models.BooleanField(null=True)
    outfield = models.BooleanField(null=True)